### PR TITLE
[WIP]Postfix Completion for Python

### PR DESCRIPTION
**Pull request by daya0576**

### CODE REVIEW

**Comment by daya0576** [comment]
@fannheyward hi, I'm trying to add postfix autocompletion for `python`, but I'm confused that it's "conflict" with language server source(pyright).
- expect: LS + Postfix
- actual: LS only

Do u know is there any way to reserve both of them? 
image


p.s. full demo:

**Comment by fannheyward** [comment]
Yes, because postfix textEdit will change `startcol`, postfix results can't be listed with LS results. I'll check this to find any better solutions.

**Comment by fannheyward** [comment]
@daya0576 I've fixed the position issue, please try v0.1.0

**Comment by daya0576** [comment]
@fannheyward thx, it works now👍, but there is a bug if deleting backwards during auto completion:

**Pull request merged**
